// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 2Pi4qcW8q34x5MEMyq2T6D

import * as React from "react";
import { hasVariant, ensureGlobalVariants } from "@plasmicapp/react-web";
import { ChakraProvider } from "@chakra-ui/react";

export interface GlobalContextsProviderProps {
  children?: React.ReactElement;
  chakraProviderProps?: Partial<
    Omit<React.ComponentProps<typeof ChakraProvider>, "children">
  >;
}

export default function GlobalContextsProvider(
  props: GlobalContextsProviderProps
) {
  const { children, chakraProviderProps } = props;

  return (
    <ChakraProvider
      {...chakraProviderProps}
      theme={
        chakraProviderProps && "theme" in chakraProviderProps
          ? chakraProviderProps.theme!
          : undefined
      }
    >
      {children}
    </ChakraProvider>
  );
}
