// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 5vAoK7BmKbFSGEzykGZNyw
// Component: Yvyy45WNSjzG

import * as React from "react";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import { ConnectWalletButton } from "suinova-nft-builder/dist/index.js";
import { WalletIcon } from "suinova-nft-builder/dist/index.js";
import { CopyIcon } from "suinova-nft-builder/dist/index.js";
import { UserIcon } from "suinova-nft-builder/dist/index.js";
import { LogoutIcon } from "suinova-nft-builder/dist/index.js";

import "@plasmicapp/react-web/lib/plasmic.css";

import plasmic_antd_5_css from "../antd_5_hostless/plasmic.module.css"; // plasmic-import: 66MC2d9B7YecVEphuUMtqF/projectcss
import projectcss from "./plasmic.module.css"; // plasmic-import: 5vAoK7BmKbFSGEzykGZNyw/projectcss
import sty from "./PlasmicHeader.module.css"; // plasmic-import: Yvyy45WNSjzG/css

import HomeSvgIcon from "./icons/PlasmicIcon__HomeSvg"; // plasmic-import: xY7bQA18AGIh/icon

createPlasmicElementProxy;

export type PlasmicHeader__VariantMembers = {};
export type PlasmicHeader__VariantsArgs = {};
type VariantPropType = keyof PlasmicHeader__VariantsArgs;
export const PlasmicHeader__VariantProps = new Array<VariantPropType>();

export type PlasmicHeader__ArgsType = {};
type ArgPropType = keyof PlasmicHeader__ArgsType;
export const PlasmicHeader__ArgProps = new Array<ArgPropType>();

export type PlasmicHeader__OverridesType = {
  root?: Flex__<"div">;
  freeBox?: Flex__<"div">;
  svg?: Flex__<"svg">;
  text?: Flex__<"div">;
  connectWalletButton?: Flex__<typeof ConnectWalletButton>;
  walletIcon?: Flex__<typeof WalletIcon>;
  copyIcon?: Flex__<typeof CopyIcon>;
  userIcon?: Flex__<typeof UserIcon>;
  logoutIconIcon?: Flex__<typeof LogoutIcon>;
};

export interface DefaultHeaderProps {
  className?: string;
}

const $$ = {};

function PlasmicHeader__RenderFunc(props: {
  variants: PlasmicHeader__VariantsArgs;
  args: PlasmicHeader__ArgsType;
  overrides: PlasmicHeader__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        projectcss.plasmic_tokens,
        plasmic_antd_5_css.plasmic_tokens,
        sty.root
      )}
    >
      <Stack__
        as={"div"}
        data-plasmic-name={"freeBox"}
        data-plasmic-override={overrides.freeBox}
        hasGap={true}
        className={classNames(projectcss.all, sty.freeBox)}
      >
        <HomeSvgIcon
          data-plasmic-name={"svg"}
          data-plasmic-override={overrides.svg}
          className={classNames(projectcss.all, sty.svg)}
          role={"img"}
        />

        <div
          data-plasmic-name={"text"}
          data-plasmic-override={overrides.text}
          className={classNames(
            projectcss.all,
            projectcss.__wab_text,
            sty.text
          )}
        >
          {"NFT Marketplace"}
        </div>
      </Stack__>
      <ConnectWalletButton
        data-plasmic-name={"connectWalletButton"}
        data-plasmic-override={overrides.connectWalletButton}
        className={classNames("__wab_instance", sty.connectWalletButton)}
        connectText={"Connect Wallet"}
        copyIcon={
          <CopyIcon
            data-plasmic-name={"copyIcon"}
            data-plasmic-override={overrides.copyIcon}
            className={"" + " " + classNames("__wab_instance", sty.copyIcon)}
            iconColor={"#27273A"}
          />
        }
        icon={
          <WalletIcon
            data-plasmic-name={"walletIcon"}
            data-plasmic-override={overrides.walletIcon}
            className={"" + " " + classNames("__wab_instance", sty.walletIcon)}
          />
        }
        logoutIcon={
          <LogoutIcon
            data-plasmic-name={"logoutIconIcon"}
            data-plasmic-override={overrides.logoutIconIcon}
            className={
              "" + " " + classNames("__wab_instance", sty.logoutIconIcon)
            }
          />
        }
        userIcon={
          <UserIcon
            data-plasmic-name={"userIcon"}
            data-plasmic-override={overrides.userIcon}
            className={"" + " " + classNames("__wab_instance", sty.userIcon)}
          />
        }
      />
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: [
    "root",
    "freeBox",
    "svg",
    "text",
    "connectWalletButton",
    "walletIcon",
    "copyIcon",
    "userIcon",
    "logoutIconIcon"
  ],
  freeBox: ["freeBox", "svg", "text"],
  svg: ["svg"],
  text: ["text"],
  connectWalletButton: [
    "connectWalletButton",
    "walletIcon",
    "copyIcon",
    "userIcon",
    "logoutIconIcon"
  ],
  walletIcon: ["walletIcon"],
  copyIcon: ["copyIcon"],
  userIcon: ["userIcon"],
  logoutIconIcon: ["logoutIconIcon"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  freeBox: "div";
  svg: "svg";
  text: "div";
  connectWalletButton: typeof ConnectWalletButton;
  walletIcon: typeof WalletIcon;
  copyIcon: typeof CopyIcon;
  userIcon: typeof UserIcon;
  logoutIconIcon: typeof LogoutIcon;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicHeader__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicHeader__VariantsArgs;
    args?: PlasmicHeader__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicHeader__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicHeader__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicHeader__ArgProps,
          internalVariantPropNames: PlasmicHeader__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicHeader__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicHeader";
  } else {
    func.displayName = `PlasmicHeader.${nodeName}`;
  }
  return func;
}

export const PlasmicHeader = Object.assign(
  // Top-level PlasmicHeader renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    freeBox: makeNodeComponent("freeBox"),
    svg: makeNodeComponent("svg"),
    text: makeNodeComponent("text"),
    connectWalletButton: makeNodeComponent("connectWalletButton"),
    walletIcon: makeNodeComponent("walletIcon"),
    copyIcon: makeNodeComponent("copyIcon"),
    userIcon: makeNodeComponent("userIcon"),
    logoutIconIcon: makeNodeComponent("logoutIconIcon"),

    // Metadata about props expected for PlasmicHeader
    internalVariantProps: PlasmicHeader__VariantProps,
    internalArgProps: PlasmicHeader__ArgProps
  }
);

export default PlasmicHeader;
/* prettier-ignore-end */
